"""Security advisories (specification section 2.7).

Every advisory carries its source, the source's own date, a confidence level and
the disclaimer that it does not replace official guidance. In phase 1 a manager
validates one before travellers can see it, so an unvalidated draft is invisible
to the ``usuario`` role by construction, not by a template check.
"""
import logging
from datetime import timedelta

from app.extensions import db
from app.models.advisory import DISCLAIMER, SecurityAdvisory
from app.models.catalog import Country
from app.models.enums import (
    AdvisoryCategory,
    AdvisoryLevel,
    AdvisoryValidationState,
    AuditResourceType,
    RoleCode,
)
from app.services import audit_service
from app.utils.errors import ConflictError, ValidationError
from app.utils.timeutil import utcnow

logger = logging.getLogger(__name__)


def list_for_trip(actor, trip, include_expired=True):
    """A trip's advisories, filtered by what this actor may see.

    A traveller sees validated advisories only: an unreviewed draft generated by
    a model is exactly the kind of thing section 2.7 does not want presented as
    guidance.
    """
    query = SecurityAdvisory.query.filter(
        SecurityAdvisory.trip_id == trip.id,
        SecurityAdvisory.is_deleted.is_(False),
    )

    es_gestor = actor.has_role(RoleCode.GESTOR) or actor.has_role(RoleCode.ADMINISTRADOR)
    if not es_gestor:
        query = query.filter(
            SecurityAdvisory.estado_validacion == AdvisoryValidationState.VALIDADA.value
        )

    advisories = query.all()
    if not include_expired:
        advisories = [a for a in advisories if not a.is_expired]

    advisories.sort(
        key=lambda a: (
            -(a.nivel.rank if a.nivel else 0),
            str(a.categoria or ''),
        )
    )
    return advisories


def generate_for_trip(actor, trip, categorias=None):
    """Generate advisories for the trip's destinations and dates.

    Public sources are consulted first, and the model is asked to write only
    what those sources support. The result is a *draft*: nothing reaches a
    traveller until a manager validates it.
    """
    destinos = _destinations_of(trip)
    if not destinos:
        raise ValidationError(
            'El viaje no tiene destinos registrados, por lo que no es posible '
            'generar recomendaciones.'
        )

    if trip.inicio_utc is None or trip.fin_utc is None:
        raise ValidationError(
            'El viaje no tiene fechas completas; las recomendaciones dependen del '
            'destino y de las fechas.'
        )

    from app.services import ai_service

    retiradas = _retirar_anteriores(actor, trip)

    created = []
    for destino in destinos:
        try:
            fuentes = _consultar_fuentes(destino, trip, actor)
        except Exception as exc:
            logger.warning('No se pudieron consultar fuentes para %s: %s', destino, exc)
            fuentes = []

        fuentes = _fuentes_sobre(fuentes, destino)
        if not fuentes:
            # The primary defence, and the one that needs no reference data:
            # a source that never names the destination cannot support an
            # advisory about it. Skipping the model here is what stops an index
            # of every country producing a confident answer about the first one.
            created.append(_no_sources_advisory(
                actor, trip, destino,
                motivo=(
                    'Ninguna fuente autorizada devolvió información sobre este '
                    'destino.'
                ),
            ))
            continue

        try:
            analysis = ai_service.analyze_risks(
                actor, trip, contexto_publico=fuentes, lugares=_nombres_de(destino),
            )
        except Exception as exc:
            logger.exception('Falló el análisis de riesgos de %s', destino)
            created.append(_no_sources_advisory(actor, trip, destino, motivo=str(exc)))
            continue

        aceptados = 0
        for riesgo in analysis.get('riesgos', []):
            ajeno = _pais_ajeno(riesgo, destino)
            if ajeno:
                # Refused, not corrected. An advisory about the wrong country is
                # worse than none: it is confidently wrong about the one thing a
                # traveller would act on.
                logger.warning(
                    'Recomendación descartada para %s: hablaba de %s.',
                    destino.pais_codigo, ajeno,
                )
                continue
            created.append(_build_advisory(actor, trip, destino, riesgo, fuentes,
                                           analysis.get('run_id')))
            aceptados += 1

        if not aceptados:
            created.append(_no_sources_advisory(
                actor, trip, destino,
                motivo=(
                    'Las fuentes consultadas no aportaron información sobre este '
                    'destino, o lo que devolvieron se refería a otro país.'
                ),
            ))

    db.session.commit()

    if retiradas:
        logger.info(
            'Se retiraron %s recomendaciones anteriores del viaje %s.',
            retiradas, trip.id,
        )

    audit_service.record(
        'advisory.generated',
        recurso_tipo=AuditResourceType.RECOMENDACION,
        recurso_id=str(trip.id),
        actor=actor,
        metadatos={'trip_id': str(trip.id), 'generadas': len(created)},
    )
    return created


def _destinations_of(trip):
    """Distinct destinations of a trip, as ``(pais, ciudad, destino)`` tuples."""
    seen = set()
    result = []
    for destination in trip.destinations:
        if destination.es_escala:
            continue
        key = (destination.pais_codigo, destination.ciudad)
        if key in seen or not any(key):
            continue
        seen.add(key)
        result.append(destination)
    return result


def _query_for(destino, trip):
    lugar = destino.ciudad or destino.pais_nombre or destino.pais_codigo
    return (
        f'recomendaciones de viaje, seguridad, sanidad y requisitos de entrada '
        f'para {lugar} en las fechas del viaje'
    )


def _estado_inicial():
    """How a freshly generated advisory starts.

    Section 2.7 asks for a manager to validate before publication, and that is
    still available: turning the setting off restores it. The default is the
    other way round because a queue of drafts nobody clears is not a control --
    it is a list of advisories the traveller never sees. Born validated, the
    manager's job becomes rejecting what does not apply, which is work
    proportional to the exceptions rather than to the volume.
    """
    from app.services import settings_service

    if settings_service.get_bool('RECOMENDACIONES_VALIDAR_AL_GENERAR', True):
        return AdvisoryValidationState.VALIDADA
    return AdvisoryValidationState.PENDIENTE_VALIDACION


def _retirar_anteriores(actor, trip):
    """Withdraw the advisories a previous run produced for this trip.

    Regenerating means "say again what applies now", so what the previous run
    said is superseded, not added to. Soft-deleted rather than destroyed: the
    audit trail still leads back to what was shown and to who decided on it.
    """
    anteriores = SecurityAdvisory.query.filter_by(
        trip_id=trip.id, is_deleted=False,
    ).all()
    for advisory in anteriores:
        advisory.soft_delete(actor)
    return len(anteriores)


def huella_de(contenido):
    """A digest of a page's text, for telling «changed» from «same».

    Of the text rather than the markup: a site that reorders its own scripts or
    stamps a session id into every page would otherwise look like it changed
    its travel advice every single day, and a warning that cries every day is a
    warning nobody reads.
    """
    from app.utils.hashing import sha256_text

    limpio = ' '.join((contenido or '').split())
    return sha256_text(limpio) if limpio else None


def vigilar_fuentes(actor=None, regenerar=None):
    """Re-read the sources behind live advisories and act if they moved.

    An advisory is written once and then describes a moment. Countries raise
    and lower their warnings between one trip and the next, so an advisory
    nobody revisits is a description of the day it was generated, presented as
    if it were current.

    Only trips that have not finished are checked: re-reading the sources for a
    journey that already happened spends model calls on advice nobody can act
    on any more.

    Returns ``{'revisados': n, 'cambiados': n, 'regenerados': n}``.
    """
    from app.models.enums import TRIP_CLOSED_STATES
    from app.models.trip import Trip
    from app.services import settings_service, web_research_service

    if regenerar is None:
        regenerar = settings_service.get_bool(
            'RECOMENDACIONES_REGENERAR_AL_CAMBIAR', True
        )

    resumen = {'revisados': 0, 'cambiados': 0, 'regenerados': 0}

    viajes = Trip.query.filter(
        Trip.is_deleted.is_(False),
        Trip.estado.notin_([str(e) for e in TRIP_CLOSED_STATES]),
    ).all()

    for trip in viajes:
        vivas = [a for a in trip.advisories if not a.is_deleted and a.fuentes]
        if not vivas:
            continue

        resumen['revisados'] += 1
        cambiadas = []

        # One reading per URL, however many advisories cite it.
        leidas = {}
        for advisory in vivas:
            for fuente in advisory.fuentes or []:
                url, huella = fuente.get('url'), fuente.get('huella')
                if not url or not huella:
                    continue

                if url not in leidas:
                    try:
                        leida = web_research_service.fetch(
                            url, use_cache=False, actor=actor,
                        )
                        leidas[url] = huella_de(leida.get('contenido'))
                    except Exception as exc:
                        logger.info('No se pudo revisar %s: %s', url, exc)
                        leidas[url] = None

                actual = leidas[url]
                if actual is not None and actual != huella:
                    cambiadas.append((advisory, url))
                    break

        if not cambiadas:
            continue

        resumen['cambiados'] += 1
        urls = sorted({url for _, url in cambiadas})
        logger.info(
            'Las fuentes del viaje %s han cambiado: %s', trip.id, ', '.join(urls),
        )
        audit_service.record(
            'advisory.source_changed',
            recurso_tipo=AuditResourceType.RECOMENDACION,
            recurso_id=str(trip.id),
            actor=actor,
            metadatos={'trip_id': str(trip.id), 'fuentes': urls},
        )

        if not regenerar:
            continue

        try:
            generate_for_trip(actor or trip.gestor, trip)
            resumen['regenerados'] += 1
        except Exception:
            logger.exception(
                'No se pudieron regenerar las recomendaciones del viaje %s', trip.id,
            )

    return resumen


def _consultar_fuentes(destino, trip, actor):
    """The sources for one destination, each on its own page where it has one.

    An official source answers with an index of every country and links to each
    one's page. Summarising the index says nothing about where the traveller is
    going, so the link is followed: what reaches the model is the destination's
    own text, which is what a manager expects to see quoted back.
    """
    from app.models.advisory import WebSource
    from app.services import web_research_service

    nombres = _nombres_de(destino)
    fuentes = []
    for source in WebSource.query.filter_by(activa=True).order_by(
        WebSource.es_oficial.desc(), WebSource.prioridad.asc()
    ).limit(3).all():
        if not source.url_base:
            continue
        resultado = web_research_service.pagina_del_lugar(source, nombres, actor=actor)
        if resultado:
            fuentes.append(resultado)
    return fuentes


def _fuentes_sobre(fuentes, destino):
    """Only the sources that actually mention this destination."""
    from app.services.web_research_service import fragmento_sobre

    nombres = _nombres_de(destino)
    return [
        fuente for fuente in fuentes
        if fragmento_sobre(fuente.get('contenido', ''), nombres)
    ]


def _nombres_de(destino):
    """Every way this destination might be named in a public source.

    Country first: an official source files travel advice by country, while
    the capital also names an embassy, a consulate and a trade office. Asking
    for «Londres» first found the embassy.

    The English name goes in too. Half the authorised sources are in English
    and file the United Kingdom under «united-kingdom»; a destination named
    only in Spanish cannot be recognised on any of their pages.
    """
    nombres = [destino.pais_nombre, destino.ciudad]

    if destino.pais_codigo:
        fila = Country.query.filter_by(codigo=destino.pais_codigo).first()
        if fila is not None and fila.nombre_en:
            nombres.append(fila.nombre_en)
        nombres.append(destino.pais_codigo)

    return [n for n in nombres if n]


def _pais_ajeno(riesgo, destino):
    """The country a risk is about, when that is not the destination's.

    Second line of defence, behind the source filtering that keeps a page
    about another country from reaching the model at all. Best effort by
    construction: it can only recognise a country the catalogue holds, and the
    catalogue is a working set rather than the full ISO list, so this narrows
    the gap without closing it.

    Returns the offending country's name, or None when the risk is either about
    the destination or about no country the catalogue knows.
    """
    texto = ' '.join(str(riesgo.get(campo) or '') for campo in
                     ('titulo', 'descripcion', 'justificacion')).lower()
    if not texto.strip():
        return None

    propios = {str(n).lower() for n in _nombres_de(destino)}
    if any(nombre and nombre in texto for nombre in propios):
        return None

    for pais in Country.query.all():
        nombre = (pais.nombre or '').strip()
        if len(nombre) < 4 or pais.codigo == destino.pais_codigo:
            continue
        if nombre.lower() in texto:
            return nombre
    return None


def _build_advisory(actor, trip, destino, riesgo, fuentes, run_id):
    """Turn one analysed risk into a draft advisory."""
    principal = next((f for f in fuentes if f.get('es_oficial')), fuentes[0])
    matched = next(
        (f for f in fuentes if riesgo.get('fuente_url') and f['url'] == riesgo['fuente_url']),
        principal,
    )

    advisory = SecurityAdvisory(
        trip_id=trip.id,
        trip_destination_id=destino.id,
        pais_codigo=destino.pais_codigo,
        ciudad=destino.ciudad,
        categoria=AdvisoryCategory.coerce(
            riesgo.get('categoria'), AdvisoryCategory.SEGURIDAD
        ),
        nivel=AdvisoryLevel.coerce(riesgo.get('nivel'), AdvisoryLevel.NORMAL),
        titulo=str(riesgo.get('titulo', 'Recomendación'))[:300],
        contenido=riesgo.get('descripcion', ''),
        recomendaciones=riesgo.get('acciones') or [],
        aplica_desde=trip.inicio_utc,
        aplica_hasta=trip.fin_utc,
        fuente=matched.get('fuente'),
        fuente_url=matched.get('url'),
        consultado_en=utcnow(),
        confianza=riesgo.get('confianza'),
        fuentes=[
            {
                'url': f['url'],
                'titulo': f.get('titulo'),
                'fuente': f.get('fuente'),
                'es_oficial': f.get('es_oficial', False),
                'consultado_en': f.get('consultado_en'),
                # The exact state of the page this advice was written from.
                # Without it «¿sigue diciendo lo mismo?» has no answer, and an
                # advisory quietly becomes a description of last month.
                'huella': huella_de(f.get('contenido')),
            }
            for f in fuentes
        ],
        caduca_en=_expiry(),
        estado_validacion=_estado_inicial(),
        generado_por_id=actor.id,
    )
    db.session.add(advisory)
    return advisory


def _no_sources_advisory(actor, trip, destino, motivo=None):
    """Record that no source could be consulted, rather than staying silent.

    A manager must be able to tell "no risks found" from "we could not check",
    so the absence of information is itself recorded as a draft advisory.
    """
    advisory = SecurityAdvisory(
        trip_id=trip.id,
        trip_destination_id=destino.id,
        pais_codigo=destino.pais_codigo,
        ciudad=destino.ciudad,
        categoria=AdvisoryCategory.OTRO,
        nivel=AdvisoryLevel.NORMAL,
        titulo=f'Sin información de fuentes autorizadas para {destino.etiqueta}',
        contenido=(
            'No ha sido posible obtener información de las fuentes públicas '
            'autorizadas para este destino. Consulte directamente los avisos '
            'oficiales antes del viaje.'
            + (f'\n\nDetalle técnico: {motivo}' if motivo else '')
        ),
        aplica_desde=trip.inicio_utc,
        aplica_hasta=trip.fin_utc,
        confianza=0.0,
        consultado_en=utcnow(),
        caduca_en=_expiry(),
        estado_validacion=AdvisoryValidationState.PENDIENTE_VALIDACION,
        generado_por_id=actor.id,
    )
    db.session.add(advisory)
    return advisory


def validate(actor, advisory, aprobar=True, comentario=None, commit=True):
    """Validate or reject an advisory (specification section 2.7)."""
    if advisory.estado_validacion is AdvisoryValidationState.VALIDADA and aprobar:
        raise ConflictError('Esta recomendación ya está validada.')

    advisory.estado_validacion = (
        AdvisoryValidationState.VALIDADA if aprobar
        else AdvisoryValidationState.RECHAZADA
    )
    advisory.validado_por_id = actor.id
    advisory.validado_en = utcnow()
    advisory.comentario_validacion = comentario

    if commit:
        db.session.commit()
        audit_service.record(
            'advisory.validated' if aprobar else 'advisory.rejected',
            recurso_tipo=AuditResourceType.RECOMENDACION,
            recurso_id=str(advisory.id),
            actor=actor,
            metadatos={
                'trip_id': str(advisory.trip_id),
                'nivel': str(advisory.nivel),
                'fuente': advisory.fuente,
            },
        )
    return advisory


def create_manual(actor, trip, titulo, contenido, categoria=None, nivel=None,
                  fuente=None, fuente_url=None, destino=None, commit=True):
    """Let a manager write an advisory by hand.

    Validated on creation: a manager writing it *is* the validation step.
    """
    advisory = SecurityAdvisory(
        trip_id=trip.id,
        trip_destination_id=destino.id if destino is not None else None,
        pais_codigo=destino.pais_codigo if destino is not None else None,
        ciudad=destino.ciudad if destino is not None else None,
        categoria=AdvisoryCategory.coerce(categoria, AdvisoryCategory.SEGURIDAD),
        nivel=AdvisoryLevel.coerce(nivel, AdvisoryLevel.NORMAL),
        titulo=str(titulo)[:300],
        contenido=contenido,
        fuente=fuente or f'{actor.nombre_completo} (redacción manual)',
        fuente_url=fuente_url,
        fecha_fuente=utcnow(),
        consultado_en=utcnow(),
        confianza=1.0,
        aplica_desde=trip.inicio_utc,
        aplica_hasta=trip.fin_utc,
        caduca_en=_expiry(),
        estado_validacion=AdvisoryValidationState.VALIDADA,
        generado_por_id=actor.id,
        validado_por_id=actor.id,
        validado_en=utcnow(),
    )
    db.session.add(advisory)

    if commit:
        db.session.commit()
        audit_service.record(
            'advisory.created_manually',
            recurso_tipo=AuditResourceType.RECOMENDACION,
            recurso_id=str(advisory.id),
            actor=actor,
            metadatos={'trip_id': str(trip.id)},
        )
    return advisory


def expire_stale(commit=True):
    """Mark advisories past their expiry as ``caducada``.

    Run by the scheduled maintenance task. Stale destination guidance presented
    as current is worse than none at all.
    """
    now = utcnow()
    stale = SecurityAdvisory.query.filter(
        SecurityAdvisory.is_deleted.is_(False),
        SecurityAdvisory.caduca_en.isnot(None),
        SecurityAdvisory.caduca_en < now,
        SecurityAdvisory.estado_validacion == AdvisoryValidationState.VALIDADA.value,
    ).all()

    for advisory in stale:
        advisory.estado_validacion = AdvisoryValidationState.CADUCADA

    if commit and stale:
        db.session.commit()
    return len(stale)


def _expiry():
    from app.services import settings_service

    days = settings_service.get_int('RECOMENDACIONES_CADUCIDAD_DIAS', 30)
    return utcnow() + timedelta(days=days)


def disclaimer():
    """The warning shown with every advisory (section 2.7)."""
    return DISCLAIMER
