"""proveedor de IA por defecto

Marca cuál de los proveedores configurados atiende las tareas que no tienen
asignación propia. Antes se decidía por la variable de entorno
AI_DEFAULT_PROVIDER; ahora se configura desde Administración, de modo que
cambiar de modelo o de proveedor no exige tocar el despliegue.

El valor por defecto es falso: la siembra marca el proveedor local inicial.


Revision ID: 0002_ia_por_defecto
Revises: 0001_esquema_inicial
Create Date: 2026-09-19 17:54:32.739656

"""
from alembic import op
import sqlalchemy as sa

# In scope for the project's custom column types (GUID, JSONBType), which
# Alembic renders by their full dotted path.
import app.models.base


revision = '0002_ia_por_defecto'
down_revision = '0001_esquema_inicial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_provider_configs', schema=None) as batch_op:
        # server_default para que la columna pueda añadirse a una tabla que ya
        # tenga proveedores configurados: sin él, NOT NULL falla al migrar.
        batch_op.add_column(sa.Column(
            'es_por_defecto', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ))
        batch_op.create_index(batch_op.f('ix_ai_provider_configs_es_por_defecto'), ['es_por_defecto'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_provider_configs_es_por_defecto'))
        batch_op.drop_column('es_por_defecto')

    # ### end Alembic commands ###
