"""varios servicios por documento

Un documento describe uno o varios servicios: un billete de ida y vuelta son
dos vuelos en un mismo correo, y una reserva de hotel puede cubrir dos
habitaciones con fechas distintas. Hasta ahora solo se guardaba el primero.

Esta columna dice cuál de los servicios del documento es cada elemento del
itinerario. Sin ella, volver a aprobar una extracción haría coincidir todos los
servicios con la misma fila y el segundo vuelo pisaría al primero.

Es anulable: los elementos introducidos a mano no proceden de ningún documento,
y los creados antes de este cambio son, por definición, el único servicio de
su documento.


Revision ID: 0003_varios_servicios
Revises: 0002_ia_por_defecto
Create Date: 2026-09-19 22:50:02.178408

"""
from alembic import op
import sqlalchemy as sa

# In scope for the project's custom column types (GUID, JSONBType), which
# Alembic renders by their full dotted path.
import app.models.base


revision = '0003_varios_servicios'
down_revision = '0002_ia_por_defecto'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento_origen_indice', sa.Integer(), nullable=True))

    with op.batch_alter_table('other_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento_origen_indice', sa.Integer(), nullable=True))

    with op.batch_alter_table('travel_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento_origen_indice', sa.Integer(), nullable=True))

    with op.batch_alter_table('vehicle_rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento_origen_indice', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_rentals', schema=None) as batch_op:
        batch_op.drop_column('documento_origen_indice')

    with op.batch_alter_table('travel_segments', schema=None) as batch_op:
        batch_op.drop_column('documento_origen_indice')

    with op.batch_alter_table('other_services', schema=None) as batch_op:
        batch_op.drop_column('documento_origen_indice')

    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_column('documento_origen_indice')

    # ### end Alembic commands ###
